# Generated by Django 4.2.3 on 2023-12-01 13:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basemodel',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quizzy.basemodel')),
                ('category_name', models.TextField()),
            ],
            bases=('quizzy.basemodel',),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quizzy.basemodel')),
                ('question_text', models.TextField()),
                ('marks', models.IntegerField(default=5)),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizzy.category')),
            ],
            bases=('quizzy.basemodel',),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quizzy.basemodel')),
                ('answer_text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizzy.question')),
            ],
            bases=('quizzy.basemodel',),
        ),
    ]
