# Generated by Django 4.2.3 on 2023-12-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzy', '0003_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
